### PR TITLE
Move over to CMake

### PR DESCRIPTION
**Pull request by tim241**
TODO:

- [x] Make elkhound compile with CMake
- [x] Move over elkhound examples
- [x] Move over tests & integrate them with CMake
* * [x] smbase tests
* * [x] ast tests
* * [x] elkhound tests
- [x] Figure out why TESTING and EXTRAS aren't global
- [x] Windows testing
- [x] Cleanup

Removed tests
=======
* smbase 
* * tmalloc

I've removed the above tests due to them being broken.

### CODE REVIEW

**Comment by FredrikLindgren** [comment]
The srcloc test seems to work. It prints so to the terminal, at any rate.

**Comment by FredrikLindgren** [comment]
The `crc32` function seems to return borked values. /usr/bin/crc32 and [libcrc](https://github.com/lammertb/libcrc) both agree on the value of $THING and smbase/crc returns some other wacky value.

**Comment by FredrikLindgren** [comment]
Ok :smile:

If you have not taken care of it already, I propose the following for fixing the array-bounds warning GCC issues over the default array lookup in deallocateTerminalValue:
```
diff --git a/src/elkhound/gramanl.cc b/src/elkhound/gramanl.cc
index caa21f7..db73b67 100644
--- a/src/elkhound/gramanl.cc
+++ b/src/elkhound/gramanl.cc
@@ -4788,8 +4788,19 @@ void emitSwitchCode(Grammar const &g, EmitCode &out,
         }
         else {
           // use the terminal map
-          out << "      std::cout << \"WARNING: there is no action to deallocate terminal \"\n"
-                 "           << termNames[" << switchVar << "] << std::endl;\n";
+
+          // Using 0 for arrayMin might perhaps not be safe; I don't
+          // know if the code can ever generate valid indices less
+          // than 0. But if it turns out to be a bad choice, it can be
+          // fixed by reducing the syms list to its least index and
+          // emitting that instead. /FL
+          out <<
+            "      int arrayMin = 0;\n"
+            "      int arrayMax = " << syms.count() << ";\n"
+            "      xassert(" << switchVar << " >= arrayMin &&"
+            " " << switchVar << " < arrayMax);\n"
+            "      std::cout << \"WARNING: there is no action to deallocate terminal \"\n"
+            "        << termNames[" << switchVar << "] << std::endl;\n";
         }
       }
       else {
```
I chose assert as it seems to me the only way the array lookup could be out-of-bounds would be because of a bug in elkhound, so it's similar to the `referenceCount > 0` assertion that is killing the elkhound test series now.

I plan to look into the failing test next.

**Comment by tim241** [comment]
I'm not sure if you agree with this, but it can be reverted easily:

I re-wrote [make-tok](https://raw.githubusercontent.com/WeiDUorg/elkhound/master/src/elkhound/make-tok) in bash because I'm better at bash than perl

**Comment by FredrikLindgren** [comment]
Is it necessary to rewrite the scripts? Seems like a lot less work if they could be left as they are. Might also be easier for someone if they ever decide to try to port to another tool chain.

**Comment by tim241** [comment]
it's not necessary, I'll revert it! (That's why I asked it anyways :+1: )

**Comment by tim241** [comment]
Alright, the [scannerless](https://github.com/WeiDUorg/elkhound/tree/master/src/elkhound/examples/scannerless) test seems broken

on the old configure & make
```
» scannerless (master) echo "a aa a aaa" | ./sless
In state 0, I expected one of these tokens:
  "" (0), "\n" (10), " " (32), "(" (40), "f" (102), "i" (105), 
Segmentation fault
» scannerless (master) echo $?
139
» scannerless (master) 
```

on cmake:
```
» scannerless (cmake) echo "a aa a aaa" | ./sless
In state 0, I expected one of these tokens:
  "" (0), "\n" (10), " " (32), "(" (40), "f" (102), "i" (105), 
<noloc>:1:1: Parse error (state 0) at "a" (97)
parse error
» scannerless (cmake) echo $?
2
» scannerless (cmake) 
```

it does require patching before you can compile it though(it still uses the old `iostream.h` and `string.h`)

**Comment by FredrikLindgren** [comment]
Broken, indeed. It's segfaulting while trying to print the error message. Exclude it for now, I guess, and I'll have a look later. There seems to be at least 2 bugs here: parse error and the segfault.

**Comment by FredrikLindgren** [comment]
Seems kind of unfinished. Nothing seems to be doing anything with it. Maybe you should omit it, for now?
Anyway, the problem with the in-file has been fixed in dc8f2d0fa197473c605f588ba9c676188be50b8a. Error, text extends beyond right margin. It's not a robust system, but it if works for the current files, it should be good enough.

**Comment by tim241** [comment]
Shouldn't it be removed then, since it's incomplete?

**Comment by FredrikLindgren** [comment]
Sorry, I did not check the resulting .gr file. It still does not parse successfully. Yeah, axe it.

**Comment by FredrikLindgren** [comment]
Yeah, let's.

**Comment by FredrikLindgren** [comment]
As long as there as C/C++ parsers, I think there should be tests for them. I think I might perhaps have been a bit hasty in thinking they should move out. There isn't really a good place for them to move and maybe having them in the project will act as another safe-guard for code quality. Thus far, they have not been a burden; all the technical debt has been has been in smbase, ast and elkhound itself. 

I'm inclined to say leave them in for now, but is it a lot of work moving them over to cmake? I'd prefer if elkhound was the default build target, perhaps the static library as well, if it's a bother sorting out the dependencies for the other targets, and the C/C++ parsers as their own targets. The test target would need to depend on the others, or there would need to be a separate target for the parser tests, which does seem like a bother.

What do you think?
(Don't worry about asking questions! :smile:)

**Comment by tim241** [comment]
Alright, I'll port everything over then, by default everything will be built, however there are flags to disable stuff to get a minimal build. i.e by using 
```
mkdir build && cd build
cmake ../src -DBUILD_TESTING=FALSE -DEXTRAS=FALSE
make
```
which builds `libast.a`, `libsmbase.a`, `astgen`, `libelkhound.a` and `elkhound`

if you want to enable the c/c++ parser, you need to do this:
```
mkdir build && cd build
cmake ../src -DBUILD_TESTING=OFF -DEXTRAS=ON
make
```
which builds `libast.a`, `libsmbase.a`, `astgen`, `libelkhound.a`, `elkhound`, `libcparse`, `cparse`, `cc2`, `cexp` and the examples

You can play with the variables to get things on/off.

**Comment by tim241** [comment]
[occ2](https://github.com/WeiDUorg/elkhound/tree/master/src/elkhound/ocaml/occ2) looks incomplete, shall we axe that one? [it seems unused](https://github.com/WeiDUorg/elkhound/search?q=occ2&unscoped_q=occ2) and doesn't build an executable

**Comment by tim241** [comment]
[in](https://github.com/WeiDUorg/elkhound/tree/master/src/elkhound/in) also looks unused.

**Comment by FredrikLindgren** [comment]
I'd prefer to keep occ2. It may not produce an executable, but for all I know, it's a functional C++ parser; so a useful example. You can compile it as far as object code by fixing up the -ocaml option to elkhound and removing the declaration from the .gr file and linking it against `..`. You don't need to give it a cmakeover; since it does not do anything and is not included anywhere I think it's fine retaining a simple Makefile. I can do the fix-up if you wish.

Three files in `in` seem to be used, from a simple grep. They aren't doing any harm now, so I'd prefer to leave the directory as it is. If it turns out to be a problem in the future, the decision can be re-evaluated.

**Comment by tim241** [comment]
Alright, that should mean that I can begin a global cleanup now(in the CMakeLists.txt files), can you also try to check the changes to make sure everything is to your liking?

**Comment by FredrikLindgren** [comment]
Looks good. A few things, however:

- I'd like to keep the following scripts, as they are potentially useful and otherwise harmless:
  * elkhound/make-lrtable-graph
  * elkhound/perf
  * elkhound/test-mlsstr-on-many
  * smbase/check-malloc-trace.pl
  * smbase/codepatch.pl
  * smbase/do-strhash-test
  * smbase/scan-depends.pl

Some of them are broken but can probably be fixed.

- Maybe keep smbase/run-flex.pl, as well. It builds successfully without, but there are differences in the output and the script might be useful for future reference.

- I assume elkhound/find-extra-deps and smbase/depend.pl are redundant now?

What do you mean by global cleanup? If it involves deleting files, I think you should use another PR for that. Let's get this merged :smile:

**Comment by tim241** [comment]
Should I put the scripts in `src/scripts` ?

**Comment by tim241** [comment]
Also, regarding `occ2`, that `Makefile` will become invalid once we switch to `cmake` (because the building is different), I see a few things I can do about that:

1: I make a CMakeLists.txt for it
2: we fix the `Makefile` to make it work with the current buildsystem
3: we add a build script
4: We remove the build stuff and just add a README which tells you how to build it

**Comment by FredrikLindgren** [comment]
> Should I put the scripts in `src/scripts` ?

Yeah, might as well.

> Also, regarding `occ2`, that `Makefile` will become invalid once we switch to `cmake` 

Oh, right. Well, if it's easy to convert it to cmake, that's fine.

**Comment by tim241** [comment]
And now it can be merged if I'm correct :+1:

**Comment by FredrikLindgren** [comment]
Nice work. Thanks!

**Comment by FredrikLindgren** [comment]
Any reason for why you added those -Wno-maybe-initialized options? My compiler isn't issuing any warnings of the sort.

**Comment by tim241** [comment]
I got a warning iirc, that's why I added it, the code didn't look bad so I just surpressed it, will provide more details later when I have access to my pc.

**Pull request merged**
